//This class was created on 2018.11.23 by Jaco van Stryp
package Graphics;

import handle.dbLocationManager;
import javax.swing.JOptionPane;


/**
 *
 * @author Jaco van Stryp
 */
public class Administration extends javax.swing.JFrame {

    /**
     * Creates new form MainUserInterface
     */
    dbLocationManager cm = new dbLocationManager();
    public Administration() {
       
                    initComponents();
     
    }

    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regNewCulEve = new javax.swing.JButton();
        btnVote3 = new javax.swing.JButton();
        btnVote4 = new javax.swing.JButton();
        btnVote5 = new javax.swing.JButton();
        btnVote6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eduplex Book Management System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 8, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eduplex Culture Management System - Administration");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Eduplex EVS v5 Small.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 67, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 477, 8, 24));

        regNewCulEve.setBackground(new java.awt.Color(255, 89, 33));
        regNewCulEve.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regNewCulEve.setForeground(new java.awt.Color(255, 255, 255));
        regNewCulEve.setText("Register New Culture Event");
        regNewCulEve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNewCulEveActionPerformed(evt);
            }
        });
        jPanel1.add(regNewCulEve, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 300, 70));

        btnVote3.setBackground(new java.awt.Color(255, 89, 33));
        btnVote3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote3.setForeground(new java.awt.Color(255, 255, 255));
        btnVote3.setText("Settings");
        btnVote3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 300, 70));

        btnVote4.setBackground(new java.awt.Color(255, 89, 33));
        btnVote4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote4.setForeground(new java.awt.Color(255, 255, 255));
        btnVote4.setText("Review Reports");
        btnVote4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 300, 70));

        btnVote5.setBackground(new java.awt.Color(255, 89, 33));
        btnVote5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote5.setForeground(new java.awt.Color(255, 255, 255));
        btnVote5.setText("Add Student");
        btnVote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 700, 70));

        btnVote6.setBackground(new java.awt.Color(255, 89, 33));
        btnVote6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote6.setForeground(new java.awt.Color(255, 255, 255));
        btnVote6.setText("Remove Culture Event");
        btnVote6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 300, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //Code will log the user out and then close the program

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
      
    }//GEN-LAST:event_jLabel15MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //This is used so the user can drag the window around without it having an frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MouseReleased

    private void regNewCulEveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNewCulEveActionPerformed
        new RegNewCultureEvent().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regNewCulEveActionPerformed

    private void btnVote3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote3ActionPerformed
        new Settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVote3ActionPerformed

    private void btnVote4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote4ActionPerformed
        new Report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVote4ActionPerformed

    private void btnVote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote5ActionPerformed
            cm.cloneEventsToLocal();
      
        new GradeSelection().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnVote5ActionPerformed

    
    
    private void btnVote6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote6ActionPerformed
        new DeleteEventManagerMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVote6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVote3;
    private javax.swing.JButton btnVote4;
    private javax.swing.JButton btnVote5;
    private javax.swing.JButton btnVote6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton regNewCulEve;
    // End of variables declaration//GEN-END:variables
}
