//This class was created on 2018.11.23 by Jaco van Stryp
package Graphics;

import handle.dbLocationManager;
import java.awt.FlowLayout;
import java.awt.print.PrinterException;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Jaco van Stryp
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form MainUserInterface
     */
    dbLocationManager cm = new dbLocationManager();
    String dbLocation = cm.getDatabaseLocation();

    public Report() {
        initComponents();
        this.loadAllBookData();
        mainReport.setCaretPosition(0);

    }

    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVote8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainReport = new javax.swing.JTextArea();
        btnVote9 = new javax.swing.JButton();
        g8v1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        eventGrade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnVote10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnVote11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eduplex Book Management System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 8, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, -1, -1));

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Eduplex EVS v5 Small.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eduplex Book Management System");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 67, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 477, 8, 24));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Leave Event Blank To Display All Information For The Selected Grade");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, -1, 30));

        btnVote8.setBackground(new java.awt.Color(255, 89, 33));
        btnVote8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote8.setForeground(new java.awt.Color(255, 255, 255));
        btnVote8.setText("Display All Information");
        btnVote8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 510, 40));

        mainReport.setBackground(new java.awt.Color(34, 34, 78));
        mainReport.setColumns(20);
        mainReport.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        mainReport.setForeground(new java.awt.Color(255, 255, 255));
        mainReport.setRows(5);
        jScrollPane1.setViewportView(mainReport);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1100, 410));

        btnVote9.setBackground(new java.awt.Color(255, 89, 33));
        btnVote9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote9.setForeground(new java.awt.Color(255, 255, 255));
        btnVote9.setText("Print");
        btnVote9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, 260, 50));

        g8v1.setBackground(new java.awt.Color(34, 34, 78));
        g8v1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        g8v1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(g8v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 270, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Report");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        eventGrade.setBackground(new java.awt.Color(37, 37, 103));
        eventGrade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eventGrade.setForeground(new java.awt.Color(255, 255, 255));
        eventGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "Teacher" }));
        jPanel1.add(eventGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 300, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Grade -");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, 30));

        btnVote10.setBackground(new java.awt.Color(255, 89, 33));
        btnVote10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote10.setForeground(new java.awt.Color(255, 255, 255));
        btnVote10.setText("Main Menu");
        btnVote10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 510, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Event -");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, -1, 30));

        btnVote11.setBackground(new java.awt.Color(255, 89, 33));
        btnVote11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote11.setForeground(new java.awt.Color(255, 255, 255));
        btnVote11.setText("Search");
        btnVote11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //Code will log the user out and then close the program

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed

    }//GEN-LAST:event_jLabel15MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //This is used so the user can drag the window around without it having an frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MouseReleased

    private void btnVote8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote8ActionPerformed
        this.loadAllBookData();
        mainReport.setCaretPosition(0);

    }//GEN-LAST:event_btnVote8ActionPerformed

    public void printText() {
        try {
            JFrame frame = new JFrame("JTextArea Demo");
            JTextArea ta = new JTextArea(10, 20);

            JScrollPane sp = new JScrollPane(ta);

            frame.setLayout(new FlowLayout());
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(300, 220);
            frame.getContentPane().add(sp);

            frame.setVisible(false);
            ta.setText(mainReport.getText());
            ta.print();
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }

    private void btnVote9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote9ActionPerformed
        this.printText();
    }//GEN-LAST:event_btnVote9ActionPerformed

    private void btnVote10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote10ActionPerformed
        new Administration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVote10ActionPerformed

    private void btnVote11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote11ActionPerformed

        mainReport.setText("");

        try {
            String event = g8v1.getText().trim();
            if (event.equalsIgnoreCase("")) {
                String s = eventGrade.getSelectedItem().toString();

                String dir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s;//Loads Folder

                mainReport.append("\n\nGrade - " + s + "\n___________________________________________\n\n");

                dir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s;//Loads Folder
                File[] listOfFiles = new File(dir).listFiles(File::isDirectory);
                if (listOfFiles == null) {
                    System.err.println("Value Null");
                } else {
                    for (int i = 0; i < listOfFiles.length; i++) {
                        mainReport.append("\n\n" + listOfFiles[i].getName() + " (");
                        if (cm.isGroup(s + "", listOfFiles[i].getName()) == true) {
                            String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + listOfFiles[i].getName() + "\\Groups";//Loads Folder
                            File[] newListOfFiles = new File(newDir).listFiles();

                            if (newListOfFiles == null) {
                                System.err.println("Value Null");

                            } else {
                                mainReport.append("Groups)\n\n");
                                for (int g = 0; g < newListOfFiles.length; g++) {
                                    mainReport.append("\n- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");
                                    Scanner scFile = new Scanner(new File(newListOfFiles[g].getAbsolutePath()));
                                    while (scFile.hasNextLine()) {
                                        mainReport.append("\n\t- " + scFile.nextLine() + "\n");

                                    }
                                    scFile.close();
                                }
                            }

                        } else {
                            String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + listOfFiles[i].getName();//Loads Folder
                            File[] newListOfFiles = new File(newDir).listFiles();
                            if (newListOfFiles == null) {
                                System.err.println("Value Null");

                            } else {
                                mainReport.append("Individual)\n\n");
                                for (int g = 0; g < newListOfFiles.length; g++) {
                                    mainReport.append("\t- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");

                                }
                            }
                        }

                    }
                }

            } else {

                String s = eventGrade.getSelectedItem().toString();
                String dir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s;//Loads Folder

                mainReport.append("\n\nGrade - " + s + "\n___________________________________________\n\n");

                dir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s;//Loads Folder
                File[] listOfFiles = new File(dir).listFiles(File::isDirectory);
                if (listOfFiles == null) {
                    System.err.println("Value Null");
                } else {

                    mainReport.append("\n\n" + event + " (");
                    if (cm.isGroup(s + "", event) == true) {
                        String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + event + "\\Groups";//Loads Folder
                        File[] newListOfFiles = new File(newDir).listFiles();

                        if (newListOfFiles == null) {
                            System.err.println("Value Null");

                        } else {
                            mainReport.append("Groups)\n\n");
                            for (int g = 0; g < newListOfFiles.length; g++) {
                                mainReport.append("\n- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");
                                Scanner scFile = new Scanner(new File(newListOfFiles[g].getAbsolutePath()));
                                while (scFile.hasNextLine()) {
                                    mainReport.append("\n\t- " + scFile.nextLine() + "\n");

                                }
                                scFile.close();
                            }
                        }

                    } else {
                        String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + event;//Loads Folder
                        File[] newListOfFiles = new File(newDir).listFiles();
                        if (newListOfFiles == null) {
                            mainReport.setText("Unable To Find Information For This Search Query");

                        } else {
                            mainReport.append("Individual)\n\n");
                            for (int g = 0; g < newListOfFiles.length; g++) {
                                mainReport.append("\t- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");

                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            mainReport.setText("Unable To Find Information For This Search Query");
        }
        mainReport.setCaretPosition(0);

    }//GEN-LAST:event_btnVote11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    public void loadAllBookData() {
        System.out.println("Search Session Start");
        try {

            mainReport.setText("Eduplex Culture Management System - All Information\n\n\n");
            String dir = "";
            //SOLO EVENTS
            for (int s = 1; s < 13; s++) {
                mainReport.append("\n\nGrade - " + s + "\n___________________________________________\n\n");

                dir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s;//Loads Folder
                File[] listOfFiles = new File(dir).listFiles(File::isDirectory);
                if (listOfFiles == null) {
                    System.err.println("Value Null");
                } else {
                    for (int i = 0; i < listOfFiles.length; i++) {
                        mainReport.append("\n\n" + listOfFiles[i].getName() + " (");
                        if (cm.isGroup(s + "", listOfFiles[i].getName()) == true) {
                            String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + listOfFiles[i].getName() + "\\Groups";//Loads Folder
                            File[] newListOfFiles = new File(newDir).listFiles();

                            if (newListOfFiles == null) {
                                System.err.println("Value Null");

                            } else {
                                mainReport.append("Groups)\n\n");
                                for (int g = 0; g < newListOfFiles.length; g++) {
                                    mainReport.append("\n- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");
                                    Scanner scFile = new Scanner(new File(newListOfFiles[g].getAbsolutePath()));
                                    while (scFile.hasNextLine()) {
                                        mainReport.append("\n\t- " + scFile.nextLine() + "\n");

                                    }
                                    scFile.close();
                                }
                            }

                        } else {
                            String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + listOfFiles[i].getName();//Loads Folder
                            File[] newListOfFiles = new File(newDir).listFiles();
                            if (newListOfFiles == null) {
                                System.err.println("Value Null");

                            } else {
                                mainReport.append("Individual)\n\n");
                                for (int g = 0; g < newListOfFiles.length; g++) {
                                    mainReport.append("\t- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");

                                }
                            }
                        }

                    }
                }

            }
            String s = "Teacher";
            mainReport.append("\n\nGrade - " + s + "\n___________________________________________\n\n");

            dir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s;//Loads Folder
            File[] listOfFiles = new File(dir).listFiles(File::isDirectory);
            if (listOfFiles == null) {
                System.err.println("Value Null"); 
            } else {
                for (int i = 0; i < listOfFiles.length; i++) {
                    mainReport.append("\n\n" + listOfFiles[i].getName() + " (");
                    if (cm.isGroup(s + "", listOfFiles[i].getName()) == true) {
                        String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + listOfFiles[i].getName() + "\\Groups";//Loads Folder
                        File[] newListOfFiles = new File(newDir).listFiles();

                        if (newListOfFiles == null) {
                            System.err.println("Value Null");

                        } else {
                            mainReport.append("Groups)\n\n");
                            for (int g = 0; g < newListOfFiles.length; g++) {
                                mainReport.append("\n- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");
                                Scanner scFile = new Scanner(new File(newListOfFiles[g].getAbsolutePath()));
                                while (scFile.hasNextLine()) {
                                    mainReport.append("\n\t- " + scFile.nextLine() + "\n");

                                }
                                scFile.close();
                            }
                        }

                    } else {
                        String newDir = dbLocation + "\\Culture_Management_Admin\\Students\\" + "Grade_" + s + "\\" + listOfFiles[i].getName();//Loads Folder
                        File[] newListOfFiles = new File(newDir).listFiles();
                        if (newListOfFiles == null) {
                            System.err.println("Value Null");

                        } else {
                            mainReport.append("Individual)\n\n");
                            for (int g = 0; g < newListOfFiles.length; g++) {
                                mainReport.append("\t- " + newListOfFiles[g].getName().substring(0, newListOfFiles[g].getName().length() - 3) + "\n");

                            }
                        }
                    }

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("Search Session End");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVote10;
    private javax.swing.JButton btnVote11;
    private javax.swing.JButton btnVote8;
    private javax.swing.JButton btnVote9;
    private javax.swing.JComboBox<String> eventGrade;
    private javax.swing.JTextField g8v1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainReport;
    // End of variables declaration//GEN-END:variables
}
