//This class was created on 2018.11.23 by Jaco van Stryp
package Graphics;

import handle.dbLocationManager;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaco van Stryp
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form MainUserInterface
     */
    dbLocationManager cm = new dbLocationManager();

    public Settings() {
        initComponents();
        this.loadActiveServerPropperties();
    }
    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVote5 = new javax.swing.JButton();
        btnSaveSettingsToServerPropperties = new javax.swing.JButton();
        btnVote11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        GradeValueComp8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GradeValueComp9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        GradeValueComp10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        GradeValueComp11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        GradeValueComp12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        GradeValueCompT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        GradeValueComp1 = new javax.swing.JTextField();
        GradeValueComp2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        GradeValueComp3 = new javax.swing.JTextField();
        GradeValueComp4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        GradeValueComp5 = new javax.swing.JTextField();
        GradeValueComp6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        GradeValueComp7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        GradeValueMaxT = new javax.swing.JTextField();
        GradeValueMax7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        GradeValueMax6 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        GradeValueMax5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        GradeValueMax12 = new javax.swing.JTextField();
        GradeValueMax11 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        GradeValueMax4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        GradeValueMax10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        GradeValueMax3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        GradeValueMax9 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        GradeValueMax2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        GradeValueMax8 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        GradeValueMax1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eduplex Book Management System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 8, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Eduplex EVS v5 Small.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eduplex Culture Management System - Settings");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 67, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 477, 8, 24));

        btnVote5.setBackground(new java.awt.Color(208, 1, 37));
        btnVote5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote5.setForeground(new java.awt.Color(255, 255, 255));
        btnVote5.setText("Reset Student Data");
        btnVote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 260, 70));

        btnSaveSettingsToServerPropperties.setBackground(new java.awt.Color(102, 114, 237));
        btnSaveSettingsToServerPropperties.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSaveSettingsToServerPropperties.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveSettingsToServerPropperties.setText("Save & Back");
        btnSaveSettingsToServerPropperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSettingsToServerProppertiesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveSettingsToServerPropperties, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 260, 70));

        btnVote11.setBackground(new java.awt.Color(0, 102, 255));
        btnVote11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote11.setForeground(new java.awt.Color(255, 255, 255));
        btnVote11.setText("Reset Settings");
        btnVote11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 260, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The Save Button Has Been Clicked And All Programs Restarted");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Please Note - All Settings In This Section Will Be");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Can Be Up To A Maximum Of 30");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 20));

        GradeValueComp8.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp8.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp8.setText("1");
        GradeValueComp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeValueComp8ActionPerformed(evt);
            }
        });
        jPanel1.add(GradeValueComp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 80, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("8");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Compulsory Choises Per Grade");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        GradeValueComp9.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp9.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp9.setText("1");
        jPanel1.add(GradeValueComp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 80, 60));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("9");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        GradeValueComp10.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp10.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp10.setText("1");
        jPanel1.add(GradeValueComp10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 80, 60));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("10");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        GradeValueComp11.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp11.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp11.setText("1");
        GradeValueComp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeValueComp11ActionPerformed(evt);
            }
        });
        jPanel1.add(GradeValueComp11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 80, 60));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("11");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        GradeValueComp12.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp12.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp12.setText("1");
        jPanel1.add(GradeValueComp12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 80, 60));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("12");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        GradeValueCompT.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueCompT.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueCompT.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueCompT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueCompT.setText("1");
        jPanel1.add(GradeValueCompT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 80, 60));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("T & O");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        GradeValueComp1.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp1.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp1.setText("1");
        jPanel1.add(GradeValueComp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, 60));

        GradeValueComp2.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp2.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp2.setText("1");
        GradeValueComp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeValueComp2ActionPerformed(evt);
            }
        });
        jPanel1.add(GradeValueComp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 80, 60));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("1");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("2");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("3");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        GradeValueComp3.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp3.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp3.setText("1");
        jPanel1.add(GradeValueComp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, 60));

        GradeValueComp4.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp4.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp4.setText("1");
        jPanel1.add(GradeValueComp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 80, 60));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("4");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("5");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        GradeValueComp5.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp5.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp5.setText("1");
        jPanel1.add(GradeValueComp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 80, 60));

        GradeValueComp6.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp6.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp6.setText("1");
        jPanel1.add(GradeValueComp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 80, 60));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("6");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        GradeValueComp7.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueComp7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueComp7.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueComp7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueComp7.setText("1");
        jPanel1.add(GradeValueComp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 80, 60));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("7");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        GradeValueMaxT.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMaxT.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMaxT.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMaxT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMaxT.setText("30");
        jPanel1.add(GradeValueMaxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 80, 60));

        GradeValueMax7.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax7.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax7.setText("30");
        jPanel1.add(GradeValueMax7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 80, 60));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("7");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("T & O");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        GradeValueMax6.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax6.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax6.setText("30");
        jPanel1.add(GradeValueMax6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 80, 60));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("6");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("5");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        GradeValueMax5.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax5.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax5.setText("30");
        jPanel1.add(GradeValueMax5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 80, 60));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("12");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));

        GradeValueMax12.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax12.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax12.setText("30");
        jPanel1.add(GradeValueMax12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 80, 60));

        GradeValueMax11.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax11.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax11.setText("30");
        GradeValueMax11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeValueMax11ActionPerformed(evt);
            }
        });
        jPanel1.add(GradeValueMax11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 80, 60));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("11");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        GradeValueMax4.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax4.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax4.setText("30");
        jPanel1.add(GradeValueMax4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 80, 60));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("4");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        GradeValueMax10.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax10.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax10.setText("30");
        jPanel1.add(GradeValueMax10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 80, 60));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("10");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        GradeValueMax3.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax3.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax3.setText("30");
        jPanel1.add(GradeValueMax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 80, 60));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("3");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        GradeValueMax9.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax9.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax9.setText("30");
        jPanel1.add(GradeValueMax9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 80, 60));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("9");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        GradeValueMax2.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax2.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax2.setText("30");
        GradeValueMax2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeValueMax2ActionPerformed(evt);
            }
        });
        jPanel1.add(GradeValueMax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 80, 60));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("2");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        GradeValueMax8.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax8.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax8.setText("30");
        GradeValueMax8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeValueMax8ActionPerformed(evt);
            }
        });
        jPanel1.add(GradeValueMax8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 80, 60));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("8");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        GradeValueMax1.setBackground(new java.awt.Color(34, 34, 78));
        GradeValueMax1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GradeValueMax1.setForeground(new java.awt.Color(255, 255, 255));
        GradeValueMax1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GradeValueMax1.setText("30");
        jPanel1.add(GradeValueMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 80, 60));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("1");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Maximum Choices Per Grade");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Forcefully Applied To All Student Computers When");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //Code will log the user out and then close the program

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed

    }//GEN-LAST:event_jLabel15MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //This is used so the user can drag the window around without it having an frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MouseReleased

    private void btnVote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVote5ActionPerformed

    private void btnSaveSettingsToServerProppertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSettingsToServerProppertiesActionPerformed

        try {
            int valCG1 = Integer.parseInt(GradeValueComp1.getText());
            int valCG2 = Integer.parseInt(GradeValueComp2.getText());
            int valCG3 = Integer.parseInt(GradeValueComp3.getText());
            int valCG4 = Integer.parseInt(GradeValueComp4.getText());
            int valCG5 = Integer.parseInt(GradeValueComp5.getText());
            int valCG6 = Integer.parseInt(GradeValueComp6.getText());
            int valCG7 = Integer.parseInt(GradeValueComp7.getText());
            int valCG8 = Integer.parseInt(GradeValueComp8.getText());
            int valCG9 = Integer.parseInt(GradeValueComp9.getText());
            int valCG10 = Integer.parseInt(GradeValueComp10.getText());
            int valCG11 = Integer.parseInt(GradeValueComp11.getText());
            int valCG12 = Integer.parseInt(GradeValueComp12.getText());
            int valCGT = Integer.parseInt(GradeValueCompT.getText());

            int valMG1 = Integer.parseInt(GradeValueMax1.getText());
            int valMG2 = Integer.parseInt(GradeValueMax2.getText());
            int valMG3 = Integer.parseInt(GradeValueMax3.getText());
            int valMG4 = Integer.parseInt(GradeValueMax4.getText());
            int valMG5 = Integer.parseInt(GradeValueMax5.getText());
            int valMG6 = Integer.parseInt(GradeValueMax6.getText());
            int valMG7 = Integer.parseInt(GradeValueMax7.getText());
            int valMG8 = Integer.parseInt(GradeValueMax8.getText());
            int valMG9 = Integer.parseInt(GradeValueMax9.getText());
            int valMG10 = Integer.parseInt(GradeValueMax10.getText());
            int valMG11 = Integer.parseInt(GradeValueMax11.getText());
            int valMG12 = Integer.parseInt(GradeValueMax12.getText());
            int valMGT = Integer.parseInt(GradeValueMaxT.getText());
            String dbLoc = cm.getDatabaseLocation();
            //Save Fresh Data To Appropriate Settings File
            PrintWriter printer = new PrintWriter(new FileWriter(dbLoc + "\\Culture_Management_Admin\\server.propperties"), false);
            printer.println(valCG1);
            printer.println(valCG2);
            printer.println(valCG3);
            printer.println(valCG4);
            printer.println(valCG5);
            printer.println(valCG6);
            printer.println(valCG7);
            printer.println(valCG8);
            printer.println(valCG9);
            printer.println(valCG10);
            printer.println(valCG11);
            printer.println(valCG12);
            printer.println(valCGT);
            printer.println(valMG1);
            printer.println(valMG2);
            printer.println(valMG3);
            printer.println(valMG4);
            printer.println(valMG5);
            printer.println(valMG6);
            printer.println(valMG7);
            printer.println(valMG8);
            printer.println(valMG9);
            printer.println(valMG10);
            printer.println(valMG11);
            printer.println(valMG12);
            printer.println(valMGT);
            printer.close();
            //JOptionPane.showMessageDialog(null, "All Settings Have Been Updated", "Success", JOptionPane.INFORMATION_MESSAGE);

            try {
                String dbLocNew = cm.getLocalStorageLocation();

                Scanner scFile = new Scanner(new File(cm.getDatabaseLocation() + "\\Culture_Management_Admin\\server.propperties"));
                PrintWriter printerNew = new PrintWriter(new FileWriter(dbLocNew + "\\Culture_Management_System\\server.propperties"), false);
                while (scFile.hasNextLine()) {
                    printerNew.println(scFile.nextLine());
                }
                scFile.close();
                printerNew.close();
                System.out.println("Settings Saved To Local Files");
                    new Administration().setVisible(true);
        this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please Make Sure All Information Is Filled In Correctly With A Numeric Value", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        
    
    }//GEN-LAST:event_btnSaveSettingsToServerProppertiesActionPerformed

    private void loadActiveServerPropperties() {
        try {
            String dbLoc = cm.getDatabaseLocation();

            Scanner scFile = new Scanner(new File(dbLoc + "\\Culture_Management_Admin\\server.propperties"));
            GradeValueComp1.setText(scFile.nextLine());
            GradeValueComp2.setText(scFile.nextLine());
            GradeValueComp3.setText(scFile.nextLine());
            GradeValueComp4.setText(scFile.nextLine());
            GradeValueComp5.setText(scFile.nextLine());
            GradeValueComp6.setText(scFile.nextLine());
            GradeValueComp7.setText(scFile.nextLine());
            GradeValueComp8.setText(scFile.nextLine());
            GradeValueComp9.setText(scFile.nextLine());
            GradeValueComp10.setText(scFile.nextLine());
            GradeValueComp11.setText(scFile.nextLine());
            GradeValueComp12.setText(scFile.nextLine());
            GradeValueCompT.setText(scFile.nextLine());

            GradeValueMax1.setText(scFile.nextLine());
            GradeValueMax2.setText(scFile.nextLine());
            GradeValueMax3.setText(scFile.nextLine());
            GradeValueMax4.setText(scFile.nextLine());
            GradeValueMax5.setText(scFile.nextLine());
            GradeValueMax6.setText(scFile.nextLine());
            GradeValueMax7.setText(scFile.nextLine());
            GradeValueMax8.setText(scFile.nextLine());
            GradeValueMax9.setText(scFile.nextLine());
            GradeValueMax10.setText(scFile.nextLine());
            GradeValueMax11.setText(scFile.nextLine());
            GradeValueMax12.setText(scFile.nextLine());
            GradeValueMaxT.setText(scFile.nextLine());

            scFile.close();

        } catch (Exception ex) {

        }
    }

    private void btnVote11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote11ActionPerformed
        GradeValueComp1.setText("1");
        GradeValueComp2.setText("1");
        GradeValueComp3.setText("1");
        GradeValueComp4.setText("1");
        GradeValueComp5.setText("1");
        GradeValueComp6.setText("1");
        GradeValueComp7.setText("1");
        GradeValueComp8.setText("1");
        GradeValueComp9.setText("1");
        GradeValueComp10.setText("1");
        GradeValueComp11.setText("1");
        GradeValueComp12.setText("1");
        GradeValueCompT.setText("1");

        GradeValueMax1.setText("30");
        GradeValueMax2.setText("30");
        GradeValueMax3.setText("30");
        GradeValueMax4.setText("30");
        GradeValueMax5.setText("30");
        GradeValueMax6.setText("30");
        GradeValueMax7.setText("30");
        GradeValueMax8.setText("30");
        GradeValueMax9.setText("30");
        GradeValueMax10.setText("30");
        GradeValueMax11.setText("30");
        GradeValueMax12.setText("30");
        GradeValueMaxT.setText("30");
    }//GEN-LAST:event_btnVote11ActionPerformed

    private void GradeValueComp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeValueComp11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeValueComp11ActionPerformed

    private void GradeValueComp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeValueComp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeValueComp8ActionPerformed

    private void GradeValueComp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeValueComp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeValueComp2ActionPerformed

    private void GradeValueMax11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeValueMax11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeValueMax11ActionPerformed

    private void GradeValueMax2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeValueMax2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeValueMax2ActionPerformed

    private void GradeValueMax8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeValueMax8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeValueMax8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GradeValueComp1;
    private javax.swing.JTextField GradeValueComp10;
    private javax.swing.JTextField GradeValueComp11;
    private javax.swing.JTextField GradeValueComp12;
    private javax.swing.JTextField GradeValueComp2;
    private javax.swing.JTextField GradeValueComp3;
    private javax.swing.JTextField GradeValueComp4;
    private javax.swing.JTextField GradeValueComp5;
    private javax.swing.JTextField GradeValueComp6;
    private javax.swing.JTextField GradeValueComp7;
    private javax.swing.JTextField GradeValueComp8;
    private javax.swing.JTextField GradeValueComp9;
    private javax.swing.JTextField GradeValueCompT;
    private javax.swing.JTextField GradeValueMax1;
    private javax.swing.JTextField GradeValueMax10;
    private javax.swing.JTextField GradeValueMax11;
    private javax.swing.JTextField GradeValueMax12;
    private javax.swing.JTextField GradeValueMax2;
    private javax.swing.JTextField GradeValueMax3;
    private javax.swing.JTextField GradeValueMax4;
    private javax.swing.JTextField GradeValueMax5;
    private javax.swing.JTextField GradeValueMax6;
    private javax.swing.JTextField GradeValueMax7;
    private javax.swing.JTextField GradeValueMax8;
    private javax.swing.JTextField GradeValueMax9;
    private javax.swing.JTextField GradeValueMaxT;
    private javax.swing.JButton btnSaveSettingsToServerPropperties;
    private javax.swing.JButton btnVote11;
    private javax.swing.JButton btnVote5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
